language: python
sudo: required
dist: xenial
python: "3.7"


before_install:
  - pip install poetry

install:
  - poetry install

script:
  - poetry run flake8 *.py

deploy:
  provider: script

  script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t vpce-opperator .
    - docker images
    - docker tag vpce-operator $DOCKER_USERNAME/vpce-operator:$TRAVIS_TAG
    - docker push $DOCKER_USERNAME/vpce-operator:$TRAVIS_TAG
    - docker tag vpce-operator $DOCKER_USERNAME/vpce-operator
    - docker push $DOCKER_USERNAME/vpce-operator
  on:
    tags: true
