apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpce-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: vpce-operator
  template:
    metadata:
      labels:
        application: vpce-operator
    spec:
      serviceAccountName: vcpe-operator-account
      containers:
      - name: vcpe-operator
        image: trulia/vpce-operator:latest
        env:
          # Optional way to load aws creds if Kube2iam isn't used
          - name: AWS_ACCESS_KEY_ID
            value: "{{ AWS_ACCESS_KEY_ID }}"
          - name: AWS_SECRET_ACCESS_KEY
            value: "{{ AWS_SECRET_ACCESS_KEY }}"

